// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bubblegum

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateMetadata is the `updateMetadata` instruction.
type UpdateMetadata struct {
	Root            *[32]uint8
	Nonce           *uint64
	Index           *uint32
	CurrentMetadata *MetadataArgs
	UpdateArgs      *UpdateArgs

	// [0] = [] treeAuthority
	//
	// [1] = [SIGNER] authority
	//
	// [2] = [] collectionMint
	//
	// [3] = [] collectionMetadata
	//
	// [4] = [] collectionAuthorityRecordPda
	//
	// [5] = [] leafOwner
	//
	// [6] = [] leafDelegate
	//
	// [7] = [SIGNER] payer
	//
	// [8] = [WRITE] merkleTree
	//
	// [9] = [] logWrapper
	//
	// [10] = [] compressionProgram
	//
	// [11] = [] tokenMetadataProgram
	//
	// [12] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateMetadataInstructionBuilder creates a new `UpdateMetadata` instruction builder.
func NewUpdateMetadataInstructionBuilder() *UpdateMetadata {
	nd := &UpdateMetadata{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetRoot sets the "root" parameter.
func (inst *UpdateMetadata) SetRoot(root [32]uint8) *UpdateMetadata {
	inst.Root = &root
	return inst
}

// SetNonce sets the "nonce" parameter.
func (inst *UpdateMetadata) SetNonce(nonce uint64) *UpdateMetadata {
	inst.Nonce = &nonce
	return inst
}

// SetIndex sets the "index" parameter.
func (inst *UpdateMetadata) SetIndex(index uint32) *UpdateMetadata {
	inst.Index = &index
	return inst
}

// SetCurrentMetadata sets the "currentMetadata" parameter.
func (inst *UpdateMetadata) SetCurrentMetadata(currentMetadata MetadataArgs) *UpdateMetadata {
	inst.CurrentMetadata = &currentMetadata
	return inst
}

// SetUpdateArgs sets the "updateArgs" parameter.
func (inst *UpdateMetadata) SetUpdateArgs(updateArgs UpdateArgs) *UpdateMetadata {
	inst.UpdateArgs = &updateArgs
	return inst
}

// SetTreeAuthorityAccount sets the "treeAuthority" account.
func (inst *UpdateMetadata) SetTreeAuthorityAccount(treeAuthority ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(treeAuthority)
	return inst
}

// GetTreeAuthorityAccount gets the "treeAuthority" account.
func (inst *UpdateMetadata) GetTreeAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *UpdateMetadata) SetAuthorityAccount(authority ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *UpdateMetadata) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCollectionMintAccount sets the "collectionMint" account.
func (inst *UpdateMetadata) SetCollectionMintAccount(collectionMint ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(collectionMint)
	return inst
}

// GetCollectionMintAccount gets the "collectionMint" account.
func (inst *UpdateMetadata) GetCollectionMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetCollectionMetadataAccount sets the "collectionMetadata" account.
func (inst *UpdateMetadata) SetCollectionMetadataAccount(collectionMetadata ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(collectionMetadata)
	return inst
}

// GetCollectionMetadataAccount gets the "collectionMetadata" account.
func (inst *UpdateMetadata) GetCollectionMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetCollectionAuthorityRecordPdaAccount sets the "collectionAuthorityRecordPda" account.
func (inst *UpdateMetadata) SetCollectionAuthorityRecordPdaAccount(collectionAuthorityRecordPda ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(collectionAuthorityRecordPda)
	return inst
}

// GetCollectionAuthorityRecordPdaAccount gets the "collectionAuthorityRecordPda" account.
func (inst *UpdateMetadata) GetCollectionAuthorityRecordPdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetLeafOwnerAccount sets the "leafOwner" account.
func (inst *UpdateMetadata) SetLeafOwnerAccount(leafOwner ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(leafOwner)
	return inst
}

// GetLeafOwnerAccount gets the "leafOwner" account.
func (inst *UpdateMetadata) GetLeafOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetLeafDelegateAccount sets the "leafDelegate" account.
func (inst *UpdateMetadata) SetLeafDelegateAccount(leafDelegate ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(leafDelegate)
	return inst
}

// GetLeafDelegateAccount gets the "leafDelegate" account.
func (inst *UpdateMetadata) GetLeafDelegateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPayerAccount sets the "payer" account.
func (inst *UpdateMetadata) SetPayerAccount(payer ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *UpdateMetadata) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetMerkleTreeAccount sets the "merkleTree" account.
func (inst *UpdateMetadata) SetMerkleTreeAccount(merkleTree ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(merkleTree).WRITE()
	return inst
}

// GetMerkleTreeAccount gets the "merkleTree" account.
func (inst *UpdateMetadata) GetMerkleTreeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetLogWrapperAccount sets the "logWrapper" account.
func (inst *UpdateMetadata) SetLogWrapperAccount(logWrapper ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(logWrapper)
	return inst
}

// GetLogWrapperAccount gets the "logWrapper" account.
func (inst *UpdateMetadata) GetLogWrapperAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetCompressionProgramAccount sets the "compressionProgram" account.
func (inst *UpdateMetadata) SetCompressionProgramAccount(compressionProgram ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(compressionProgram)
	return inst
}

// GetCompressionProgramAccount gets the "compressionProgram" account.
func (inst *UpdateMetadata) GetCompressionProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenMetadataProgramAccount sets the "tokenMetadataProgram" account.
func (inst *UpdateMetadata) SetTokenMetadataProgramAccount(tokenMetadataProgram ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenMetadataProgram)
	return inst
}

// GetTokenMetadataProgramAccount gets the "tokenMetadataProgram" account.
func (inst *UpdateMetadata) GetTokenMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateMetadata) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateMetadata {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateMetadata) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst UpdateMetadata) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateMetadata,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateMetadata) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateMetadata) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Root == nil {
			return errors.New("Root parameter is not set")
		}
		if inst.Nonce == nil {
			return errors.New("Nonce parameter is not set")
		}
		if inst.Index == nil {
			return errors.New("Index parameter is not set")
		}
		if inst.CurrentMetadata == nil {
			return errors.New("CurrentMetadata parameter is not set")
		}
		if inst.UpdateArgs == nil {
			return errors.New("UpdateArgs parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TreeAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CollectionMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CollectionMetadata is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.CollectionAuthorityRecordPda is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.LeafOwner is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.LeafDelegate is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.MerkleTree is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.LogWrapper is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.CompressionProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenMetadataProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *UpdateMetadata) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateMetadata")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("           Root", *inst.Root))
						paramsBranch.Child(ag_format.Param("          Nonce", *inst.Nonce))
						paramsBranch.Child(ag_format.Param("          Index", *inst.Index))
						paramsBranch.Child(ag_format.Param("CurrentMetadata", *inst.CurrentMetadata))
						paramsBranch.Child(ag_format.Param("     UpdateArgs", *inst.UpdateArgs))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               treeAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                   authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("              collectionMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("          collectionMetadata", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("collectionAuthorityRecordPda", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                   leafOwner", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                leafDelegate", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("                       payer", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                  merkleTree", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                  logWrapper", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          compressionProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("        tokenMetadataProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("               systemProgram", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj UpdateMetadata) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Root` param:
	err = encoder.Encode(obj.Root)
	if err != nil {
		return err
	}
	// Serialize `Nonce` param:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `CurrentMetadata` param:
	err = encoder.Encode(obj.CurrentMetadata)
	if err != nil {
		return err
	}
	// Serialize `UpdateArgs` param:
	err = encoder.Encode(obj.UpdateArgs)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateMetadata) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Root`:
	err = decoder.Decode(&obj.Root)
	if err != nil {
		return err
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return err
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `CurrentMetadata`:
	err = decoder.Decode(&obj.CurrentMetadata)
	if err != nil {
		return err
	}
	// Deserialize `UpdateArgs`:
	err = decoder.Decode(&obj.UpdateArgs)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateMetadataInstruction declares a new UpdateMetadata instruction with the provided parameters and accounts.
func NewUpdateMetadataInstruction(
	// Parameters:
	root [32]uint8,
	nonce uint64,
	index uint32,
	currentMetadata MetadataArgs,
	updateArgs UpdateArgs,
	// Accounts:
	treeAuthority ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	collectionMint ag_solanago.PublicKey,
	collectionMetadata ag_solanago.PublicKey,
	collectionAuthorityRecordPda ag_solanago.PublicKey,
	leafOwner ag_solanago.PublicKey,
	leafDelegate ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	merkleTree ag_solanago.PublicKey,
	logWrapper ag_solanago.PublicKey,
	compressionProgram ag_solanago.PublicKey,
	tokenMetadataProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *UpdateMetadata {
	return NewUpdateMetadataInstructionBuilder().
		SetRoot(root).
		SetNonce(nonce).
		SetIndex(index).
		SetCurrentMetadata(currentMetadata).
		SetUpdateArgs(updateArgs).
		SetTreeAuthorityAccount(treeAuthority).
		SetAuthorityAccount(authority).
		SetCollectionMintAccount(collectionMint).
		SetCollectionMetadataAccount(collectionMetadata).
		SetCollectionAuthorityRecordPdaAccount(collectionAuthorityRecordPda).
		SetLeafOwnerAccount(leafOwner).
		SetLeafDelegateAccount(leafDelegate).
		SetPayerAccount(payer).
		SetMerkleTreeAccount(merkleTree).
		SetLogWrapperAccount(logWrapper).
		SetCompressionProgramAccount(compressionProgram).
		SetTokenMetadataProgramAccount(tokenMetadataProgram).
		SetSystemProgramAccount(systemProgram)
}
